# Dockerfile for MXNet version 1.2 built from source in distributed mode
# With CUDA, CuDNN, OpenCV, OpenBlas and KVStore distributed

FROM nvidia/cuda:8.0-cudnn5-devel

RUN apt-get install -y build-essential git \
    && apt-get install -y libopenblas-dev liblapack-dev \
    && apt-get install -y libopencv-dev libopenmpi-dev \

RUN git clone --recursive https://github.com/apache/incubator-mxnet \
    && cd incubator-mxnet \
    && git checkout 1.2.0.rc3 \
    && git submodule update \
    && make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_DIST_KVSTORE=1 \
    && cd python \
    && pip install -e . \
    && pip install fire toolz jupyter scipy scikit-learn


