# To create the conda environment (codebase):
# $ conda env create -n codebase -f conda.yaml
#
# To update the conda environment:
# $ conda env update -n codebase -f conda.yaml
#
# To register the conda environment in Jupyter:
# $ python -m ipykernel install --user --name codebase --display-name "Python (codebase)"
#

channels:
- conda-forge
- defaults
dependencies:
- numpy>=1.13.3
- opencv>=3.3.0
- pyodbc>=4.0.21
- requests>=2.18.4
- beautifulsoup4>=4.6.0
- flask>=1.0.2
- cherrypy>=12.0.1
- paste>=2.0.3
- fastparquet>=0.1.4
- dask>=0.17.1
- ipykernel>=4.6.1
- pip:
  - memory_profiler>=0.47
  - pandas>=0.22.0
  - scikit-image>=0.13.1
  - scikit-learn>=0.19.1
  - scipy>=0.19.0
  - matplotlib>=1.5.3
  - bokeh>=0.12.6
  - selenium>=3.4.3
  - pillow>=4.3.0
  - sqlalchemy>=1.2.4
  - gitpython>=2.1.8
  - pytrends>=4.3.0
  - azure-storage>=0.36.0
  - pyspark>=2.3.0
  - xmlrunner>=1.7.7
  - coverage>=4.5.1
  # For websockets, add flask-socketio, gevent-websocket, wsaccel and ujson
  - flask-socketio>=3.0.1
  - gevent-websocket>=0.10.1
  - wsaccel>=0.6.2
  - ujson>=1.35
  - pytest>=3.6.3
  - papermill>=0.15.0
  - wget>=3.2



